services:
  postgres:
    image: postgres:15-alpine
    container_name: fund-management-db
    environment:
      POSTGRES_DB: fund_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fund-management-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fund_management?schema=public
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run db:push && npm run db:seed && npm run dev:container"
    stop_grace_period: 2s
    init: true

volumes:
  postgres_data:
